// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbOmQzU4jYsIzDSOKsXV70bQF03kdnUHA',
    appId: '1:3314910375:web:ba8872ab2cd31a32754782',
    messagingSenderId: '3314910375',
    projectId: 'furniture-app-b95ce',
    authDomain: 'furniture-app-b95ce.firebaseapp.com',
    storageBucket: 'furniture-app-b95ce.appspot.com',
    measurementId: 'G-M3BJXD2EFQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ721QbUXGOPtDAiGUA_SKWBO2hSA-SW8',
    appId: '1:3314910375:android:4d73424dd5862812754782',
    messagingSenderId: '3314910375',
    projectId: 'furniture-app-b95ce',
    storageBucket: 'furniture-app-b95ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_DOmH_t1wXodZcR0SYiwxXqzl6eJ17jE',
    appId: '1:3314910375:ios:95e527960494a1e2754782',
    messagingSenderId: '3314910375',
    projectId: 'furniture-app-b95ce',
    storageBucket: 'furniture-app-b95ce.appspot.com',
    iosClientId: '3314910375-ia1ks4mure8ssacdkd5fvjg41teg74dr.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_DOmH_t1wXodZcR0SYiwxXqzl6eJ17jE',
    appId: '1:3314910375:ios:914e4d3d85b87fa3754782',
    messagingSenderId: '3314910375',
    projectId: 'furniture-app-b95ce',
    storageBucket: 'furniture-app-b95ce.appspot.com',
    iosClientId: '3314910375-8kov4cvp7muk88ogc9gv1qrkiei1tamd.apps.googleusercontent.com',
    iosBundleId: 'com.example.project.RunnerTests',
  );
}
